version: "3.3"
services:
  db:
    image: josingcjx/sql-data4test:1.0
    container_name: sql-data4test
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/data
    networks:
      - data4test
    environment:
      - MYSQL_ROOT_PASSWORD:password
      - MYSQL_USER:admin
      - MYSQL_PASSWORD:data4test
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    networks:
      - data4test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
  data4test:
    image: josingcjx/data4test:1.0
    container_name: data4test
    restart: always
    depends_on:
      - db
    ports:
      - "9088:9088"
    networks:
      - data4test
    environment:
      - MYSQL_PORT:3306
      - MYSQL_HOST:db
      - MYSQL_PASSWORD:password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data4test:/data
networks:
  data4test: {}
volumes:
  portainer: {}
  mysql: {}
  data4test: {}
