version: "3.3"
services:
  db:
    image: josingcjx/db-data4test:3.0
    container_name: db-data4test
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33066:3306"
    volumes:
      - mysql:/data
    networks:
      - data4test
    environment:
      - MYSQL_ROOT_PASSWORD:password
      - MYSQL_USER:admin
      - MYSQL_PASSWORD:data4test
  data4test:
    image: josingcjx/data4test:3.0
    container_name: data4test
    restart: always
    depends_on:
      - db
    ports:
      - "9088:9088"
    networks:
      - data4test
    environment:
      - MYSQL_PORT:3306
      - MYSQL_HOST:db
      - MYSQL_PASSWORD:password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data4test:/data
networks:
  data4test: {}
volumes:
  mysql: {}
  data4test: {}